version: '3.8'

services:
  web:
    build: .
    volumes:
      - /usr/src/app/
    ports:
      - "8001:8000"
    env_file:
      - .env.dev
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=delmas
      - POSTGRES_DB=enAparte
    ports:
      - "5431:5432"  # Ajoute cette ligne pour exposer le port 5432

volumes:
  postgres_data:
