# Generated by Django 4.2.7 on 2023-11-27 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPLOYER', 'EMPLOYER'), ('CLIENT', 'CLIENT'), ('ADMIN', 'CLIENT')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nom', models.CharField(max_length=250, verbose_name='nom')),
                ('prenom', models.CharField(max_length=250)),
                ('contact', models.IntegerField(max_length=10)),
                ('commune', models.CharField(max_length=250)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Rendez_vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_attente', models.BooleanField(default=True)),
                ('confirmation', models.BooleanField(default=False)),
                ('debut', models.BooleanField(default=False)),
                ('fin', models.BooleanField(default=False)),
                ('Date_prise_rendez_vous', models.DateTimeField(blank=True, null=True)),
                ('heure_debut_rendez_vous', models.TimeField(blank=True, null=True)),
                ('heure_fin_rendez_vous', models.TimeField(blank=True, null=True)),
                ('duree_rendez_vous', models.DurationField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_clients', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_employers', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.roles')),
            ],
        ),
    ]
