# Generated by Django 4.1.13 on 2023-12-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendez_vous',
            name='etat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
