# Generated by Django 4.1.13 on 2023-12-20 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_rendez_vous_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='mon_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
