# Generated by Django 4.1.13 on 2023-11-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_alter_utilisateur_contact_alter_utilisateur_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendez_vous',
            name='roles',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.roles'),
        ),
    ]
