# Generated by Django 4.1.13 on 2023-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_remove_rendez_vous_roles_utilisateur_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendez_vous',
            name='date_rendez_vous',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='heure_rendez_vous',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='type_massage',
            field=models.CharField(choices=[('massage', 'Massage'), ('coiffure', 'Coiffure'), ('soins_peau', 'Soins de peau')], max_length=255, null=True),
        ),
    ]
