# Generated by Django 4.2.7 on 2024-01-02 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_alter_rendez_vous_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendez_vous',
            name='preference_employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_preference_employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
