# Generated by Django 4.2.7 on 2023-11-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_rendez_vous_date_rendez_vous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='date_rendez_vous',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='heure_rendez_vous',
            field=models.CharField(blank=True, choices=[('8H00-10H00', '8H00-10H00'), ('10H00-12H00', '10H00-12H00'), ('14H00-16H00', '14H00-16H00'), ('16H00-18H00', '16H00-18H00')], null=True),
        ),
    ]
