# Generated by Django 4.2.7 on 2024-01-02 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_rendez_vous_preference_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='preference_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_preference_employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
