# Generated by Django 4.1.13 on 2023-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_alter_rendez_vous_date_rendez_vous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='heure_rendez_vous',
            field=models.CharField(blank=True, choices=[('8H00-10H00', '8H00-10H00'), ('10H00-12H00', '10H00-12H00'), ('14H00-16H00', '14H00-16H00'), ('16H00-18H00', '16H00-18H00')], max_length=250, null=True),
        ),
    ]
