# Generated by Django 4.2.7 on 2023-12-06 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_alter_rendez_vous_heure_rendez_vous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confirmer', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours de traitement', 'En cours de traitement'), ('Expédiée', 'Expédiée')], default='En attente', max_length=50)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_client', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_employers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotion', models.BooleanField(default=False)),
                ('pourcentage_promotion', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produit')),
            ],
        ),
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(choices=[('EMPLOYER', 'EMPLOYER'), ('ADMIN', 'ADMIN'), ('CLIENT', 'CLIENT')], max_length=10),
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(through='Model.LigneCommande', to='Model.produit'),
        ),
    ]
