# Generated by Django 4.1.13 on 2023-12-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_alter_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_reduit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_produit/'),
        ),
    ]
