# Generated by Django 4.1.13 on 2023-12-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0010_produit_prix_reduit_alter_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_reduit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
