# Generated by Django 4.1.13 on 2023-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0011_alter_produit_prix_alter_produit_prix_reduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
