# Generated by Django 4.1.13 on 2023-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0012_alter_commande_montant_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
