# Generated by Django 4.1.13 on 2023-12-12 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0012_alter_commande_montant_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paniers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande_client', models.DateTimeField(blank=True, null=True)),
                ('date_confirmation_commande', models.DateTimeField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('confirmation_panier', models.BooleanField(default=False)),
                ('confirmation_employer', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours de traitement', 'En cours de traitement'), ('Expédiée', 'Expédiée')], default='En attente', max_length=50)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commande_employers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commande_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='commande',
            name='produits',
        ),
        migrations.AlterField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_reduit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paniers',
            name='ordre',
            field=models.ManyToManyField(to='Model.commande'),
        ),
    ]
