# Generated by Django 4.1.13 on 2023-12-12 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0013_paniers_remove_commande_confirmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paniers',
            name='date_reception_commande',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paniers',
            name='reception_commande',
            field=models.BooleanField(default=False),
        )
    ]
