# Generated by Django 4.1.13 on 2023-12-13 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0014_remove_commande_confirmer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paniers',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paniers',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_employers', to=settings.AUTH_USER_MODEL),
        )
    ]
