# Generated by Django 4.1.13 on 2023-12-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0017_produitlog_remove_commande_confirmer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        )
    ]
