# Generated by Django 4.2.7 on 2023-12-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0017_produitlog_remove_commande_confirmer_and_more'),
    ]

    operations = [

    ]
