# Generated by Django 4.2.7 on 2023-12-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0017_produitlog_remove_commande_confirmer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='confirmer',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='statut',
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.produit'),
        ),
        migrations.DeleteModel(
            name='LigneCommande',
        ),
    ]
