# Generated by Django 4.1.13 on 2023-12-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0018_remove_commande_confirmer_and_more'),
        ('Model', '0018_service_remove_commande_confirmer_and_more'),
    ]

    operations = [
    ]
