# Generated by Django 4.1.13 on 2023-12-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0019_merge_20231219_1333'),
    ]

    operations = [

        migrations.AddField(
            model_name='rendez_vous',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
