# Generated by Django 4.1.13 on 2023-12-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0021_horaire_remove_commande_confirmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaire',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='disponibilite',
            field=models.BooleanField(default=True),
        )
    ]
