# Generated by Django 4.1.13 on 2023-12-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0022_remove_commande_confirmer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendez_vous',
            name='heure_rendez_vous',
        ),
        migrations.RemoveField(
            model_name='rendez_vous',
            name='type_massage',
        )
    ]
